# Generated by Django 3.0.3 on 2020-02-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_email', models.CharField(max_length=300)),
                ('student_number', models.CharField(max_length=400)),
                ('student_address', models.TextField(max_length=500)),
                ('student_address2', models.TextField(max_length=500)),
                ('student_city', models.CharField(max_length=50)),
                ('student_state', models.CharField(max_length=50)),
                ('student_zip', models.CharField(max_length=20)),
            ],
        ),
    ]
