# Generated by Django 3.0.3 on 2020-02-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionperson',
            name='student_course',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
